   var allcountries = [
    {"CountryName":"Afghanistan",	"Rank":169	,	"MoslemPopulation":"< 1000"	,	"Percentage":99.8	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Afghanistan.png"},
    {"CountryName":"Albania"	,	"Rank":110	,	"MoslemPopulation":"2000"	,	"Percentage":82.1	,	"OIC":"Yes"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/Albania.png"},
    {"CountryName":"Algeria"	,	"Rank":160	,	"MoslemPopulation":"184000"	,	"Percentage":98.2	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Algeria.png"},
    {"CountryName":"American Samoa"	,"Rank":178	,	"MoslemPopulation":"827000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Ocenia"	,	"Developed":"No"	,	"Flag":"res/American-Samoa.png"},
    {"CountryName":"Andorra"	,	"Rank":69	,	"MoslemPopulation":"12316000"	,	"Percentage":1.1	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Andorra.png"},
    {"CountryName":"Angola"	,	"Rank":199	,	"MoslemPopulation":"26833000"	,	"Percentage":1	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Angola.png"},
    {"CountryName":"Antigua and Barbuda"	,"Rank":75	,"MoslemPopulation":"197000"	,	"Percentage":0.6	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Antigua-and-Barbuda.png"},
    {"CountryName":"Argentina"	,	"Rank":54	,	"MoslemPopulation":"2542000"	,	"Percentage":2.5	,	"OIC":"No"	,	"Continent":"South America"	,	"Developed":"No"	,	"Flag":"res/Argentina.png"},
    {"CountryName":"Armenia"	,	"Rank":114	,	"MoslemPopulation":"4737000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/Armenia.png"},
    {"CountryName":"Aruba"	,	"Rank":90	,	"MoslemPopulation":"41000"	,	"Percentage":0.4	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Aruba.png"},
    {"CountryName":"Australia"	,	"Rank":9	,	"MoslemPopulation":"28721000"	,	"Percentage":1.9	,	"OIC":"No"	,	"Continent":"Oceania"	,	"Developed":"Yes"	,	"Flag":"res/Australia.png"},
    {"CountryName":"Austria"	,	"Rank":11	,	"MoslemPopulation":"< 1000"	,	"Percentage":5.7	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Austria.png"},
    {"CountryName":"Azerbaijan"	,	"Rank":125	,	"MoslemPopulation":"2259000"	,	"Percentage":98.4	,	"OIC":"Yes"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/Azerbaijan.png"},
    {"CountryName":"Bahamas"	,	"Rank":18	,	"MoslemPopulation":"442000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Bahamas.png"},
    {"CountryName":"Bahrain"	,	"Rank":64	,	"MoslemPopulation":"2601000"	,	"Percentage":81.2	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Bahrain.png"},
    {"CountryName":"Bangladesh"	,	"Rank":152	,	"MoslemPopulation":"1002000"	,	"Percentage":90.4	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Bangladesh.png"},
    {"CountryName":"Barbados"	,	"Rank":24	,	"MoslemPopulation":"< 1000"	,	"Percentage":0.9	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Barbados.png"},
    {"CountryName":"Belarus"	,	"Rank":128	,	"MoslemPopulation":"< 1000"	,	"Percentage":0.2	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/Belarus.png"},
    {"CountryName":"Belgium"	,	"Rank":14	,	"MoslemPopulation":"4704000"	,	"Percentage":6	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Belgium.png"},
    {"CountryName":"Belize"	,	"Rank":68	,	"MoslemPopulation":"309000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Belize.png"},
    {"CountryName":"Benin"	,	"Rank":147	,	"MoslemPopulation":"204000"	,	"Percentage":24.5	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Benin.png"},
    {"CountryName":"Bermuda"	,	"Rank":166	,	"MoslemPopulation":"20895000"	,	"Percentage":0.8	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Bermuda.png"},
    {"CountryName":"Bhutan"	,	"Rank":167	,	"MoslemPopulation":"7006000"	,	"Percentage":1	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Bhutan.png"},
    {"CountryName":"Bolivia"	,	"Rank":123	,	"MoslemPopulation":"16379000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"South America"	,	"Developed":"No"	,	"Flag":"res/Bolivia.png"},
    {"CountryName":"Bosnia-Herzegovina"	,"Rank":101	,	"MoslemPopulation":"2547000"	,	"Percentage":41.6	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/Bosnia-and-Herzegovina.png"},
    {"CountryName":"Botswana"	,	"Rank":51	,	"MoslemPopulation":"4927000"	,	"Percentage":0.4	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Botswana.png"},
    {"CountryName":"Brazil"	,	"Rank":55	,	"MoslemPopulation":"1000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"South America"	,	"Developed":"No"	,	"Flag":"res/Brazil.png"},
    {"CountryName":"Brunei"	,	"Rank":65	,	"MoslemPopulation":"34780000"	,	"Percentage":51.9	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Brunei.png"},
    {"CountryName":"Bulgaria"	,	"Rank":57	,	"MoslemPopulation":"6325000"	,	"Percentage":13.4	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Bulgaria.png"},
    {"CountryName":"Burkina Faso"	,"Rank":132	,	"MoslemPopulation":"7000"	,	"Percentage":58.9	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Burkina-Faso.png"},
    {"CountryName":"Burma (Myanmar)"	,"Rank":164	,	"MoslemPopulation":"451000"	,	"Percentage":3.8	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Burma (Myanmar).png"},
    {"CountryName":"Burundi"	,	"Rank":156	,	"MoslemPopulation":"2000"	,	"Percentage":2.2	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Burundi.png"},
    {"CountryName":"Cambodia"	,	"Rank":154	,	"MoslemPopulation":"< 1000"	,	"Percentage":1.6	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Cambodia.png"},
    {"CountryName":"Cameroon"	,	"Rank":162	,	"MoslemPopulation":"240000"	,	"Percentage":18	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Cameroon.png"},
    {"CountryName":"Canada"	,	"Rank":7	,	"MoslemPopulation":"1909000"	,	"Percentage":2.8	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"Yes"	,	"Flag":"res/Canada.png"},
    {"CountryName":"Cape Verde"	,	"Rank":83	,	"MoslemPopulation":"5340000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Cape-Verde.png"},
    {"CountryName":"Cayman Islands"	,"Rank":70	,	"MoslemPopulation":"1000"	,	"Percentage":0.2	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Cayman-Islands.png"},
    {"CountryName":"Central African Republic"	,"Rank":165	,	"MoslemPopulation":"433000"	,	"Percentage":8.9	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Central-African-Republic.png"},
    {"CountryName":"Chad"	,	"Rank":197	,	"MoslemPopulation":"56000"	,	"Percentage":55.7	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Chad.png"},
    {"CountryName":"Channel Islands"	,"Rank":202	,	"MoslemPopulation":"160000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/Channel Islands.png"},
    {"CountryName":"Chile"	,	"Rank":34	,	"MoslemPopulation":"177286000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"South America"	,	"Developed":"No"	,	"Flag":"res/Chile.png"},
    {"CountryName":"China"	,	"Rank":81	,	"MoslemPopulation":"120000"	,	"Percentage":1.8	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/China.png"},
    {"CountryName":"Colombia"	,	"Rank":86	,	"MoslemPopulation":"1253000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"South America"	,	"Developed":"No"	,	"Flag":"res/Colombia.png"},
    {"CountryName":"Comoros"	,	"Rank":200	,	"MoslemPopulation":"< 1000"	,	"Percentage":98.3	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Comoros.png"},
    {"CountryName":"Congo"	,	"Rank":171	,	"MoslemPopulation":"3952000"	,	"Percentage":1.4	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Congo.png"},
    {"CountryName":"Cook Islands"	,"Rank":22	,	"MoslemPopulation":"< 1000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Oceania"	,	"Developed":"No"	,	"Flag":"res/Cook-Islands.png"},
    {"CountryName":"Costa Rica"	,	"Rank":179	,	"MoslemPopulation":"< 1000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Costa-Rica.png"},
    {"CountryName":"Croatia"	,	"Rank":43	,	"MoslemPopulation":"1000"	,	"Percentage":1.3	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/Croatia.png"},
    {"CountryName":"Cuba"	,	"Rank":149	,	"MoslemPopulation":"737000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Cuba.png"},
    {"CountryName":"Cyprus"	,	"Rank":36	,	"MoslemPopulation":"74819000"	,	"Percentage":22.7	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Cyprus.png"},
    {"CountryName":"Czech Republic"	,"Rank":20	,	"MoslemPopulation":"3906000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Czech-Republic.png"},
    {"CountryName":"Denmark"	,	"Rank":6	,	"MoslemPopulation":"28000"	,	"Percentage":4.1	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Denmark.png"},
    {"CountryName":"Djibouti"	,	"Rank":193	,	"MoslemPopulation":"969000"	,	"Percentage":97	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Djibouti.png"},
    {"CountryName":"Dominica"	,	"Rank":60	,	"MoslemPopulation":"11000"	,	"Percentage":0.2	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Dominica.png"},
    {"CountryName":"Dominican Republic"	,"Rank":87	,	"MoslemPopulation":"914000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Dominican-Republic.png"},
    {"CountryName":"Ecuador"	,	"Rank":125	,	"MoslemPopulation":"188000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"South America"	,	"Developed":"No"	,	"Flag":"res/Ecuador.png"},
    {"CountryName":"Egypt"	,	"Rank":153	,	"MoslemPopulation":"9600000"	,	"Percentage":94.7	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Egypt.png"},
    {"CountryName":"El Salvador"	,"Rank":58	,	"MoslemPopulation":"2000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/El-Salvador.png"},
    {"CountryName":"Equatorial Guinea"	,"Rank":183	,	"MoslemPopulation":"4830000"	,	"Percentage":4.1	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Equatorial-Guinea.png"},
    {"CountryName":"Eritrea"	,	"Rank":204	,	"MoslemPopulation":"24023000"	,	"Percentage":36.5	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Eritrea.png"},
    {"CountryName":"Estonia"	,	"Rank":21	,	"MoslemPopulation":"527000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Estonia.png"},
    {"CountryName":"Ethiopia"	,	"Rank":180	,	"MoslemPopulation":"78000"	,	"Percentage":33.8	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Ethiopia.png"},
    {"CountryName":"Faeroe Islands"	,"Rank":188	,	"MoslemPopulation":"3577000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"Yes"	,	"Flag":"res/Faroes.png"},
    {"CountryName":"Federated States of Micronesia"	,	"Rank":161	,	"MoslemPopulation":"2000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Oceania"	,	"Developed":"No"	,	"Flag":"res/Micronesia.png"},
    {"CountryName":"Fiji"	,	"Rank":72	,	"MoslemPopulation":"3338000"	,	"Percentage":6.3	,	"OIC":"No"	,	"Continent":"Oceania"	,	"Developed":"No"	,	"Flag":"res/Fiji.png"},
    {"CountryName":"Finland"	,	"Rank":5	,	"MoslemPopulation":"2000"	,	"Percentage":0.8	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Finland.png"},
    {"CountryName":"France"	,	"Rank":18	,	"MoslemPopulation":"4119000"	,	"Percentage":7.5	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/France.png"},
    {"CountryName":"French Polynesia"	,"Rank":181	,	"MoslemPopulation":"10349000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Oceania"	,	"Developed":"No"	,	"Flag":"res/French-Polynesia.png"},
    {"CountryName":"Gabon"	,	"Rank":75	,	"MoslemPopulation":"195000"	,	"Percentage":9.7	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Gabon.png"},
    {"CountryName":"Gambia"	,	"Rank":124	,	"MoslemPopulation":"< 1000"	,	"Percentage":95.3	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Gambia.png"},
    {"CountryName":"Georgia"	,	"Rank":117	,	"MoslemPopulation":"1000"	,	"Percentage":10.5	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/Georgia.png"},
    {"CountryName":"Germany"	,	"Rank":17	,	"MoslemPopulation":"1669000"	,	"Percentage":5	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Germany.png"},
    {"CountryName":"Ghana"	,	"Rank":53	,	"MoslemPopulation":"2000"	,	"Percentage":16.1	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Ghana.png"},
    {"CountryName":"Greece"	,	"Rank":46	,	"MoslemPopulation":"8887000"	,	"Percentage":4.7	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Greece.png"},
    {"CountryName":"Greenland"	,	"Rank":93	,	"MoslemPopulation":"75728000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Greenland.png"},
    {"CountryName":"Grenada"	,	"Rank":79	,	"MoslemPopulation":"15000"	,	"Percentage":0.3	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Grenada.png"},
    {"CountryName":"Guam"	,	"Rank":170	,	"MoslemPopulation":"13450000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Guam.png"},
    {"CountryName":"Guatemala"	,	"Rank":127	,	"MoslemPopulation":"< 1000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Guatemala.png"},
    {"CountryName":"Guinea"	,	"Rank":145	,	"MoslemPopulation":"8000"	,	"Percentage":84.2	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Guinea.png"},
    {"CountryName":"Guinea Bissau"	,"Rank":190	,	"MoslemPopulation":"679000"	,	"Percentage":42.8	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Guinea-Bissau.png"},
    {"CountryName":"Guyana"	,	"Rank":94	,	"MoslemPopulation":"1000"	,	"Percentage":7.2	,	"OIC":"Yes"	,	"Continent":"South America"	,	"Developed":"No"	,	"Flag":"res/Guyana.png"},
    {"CountryName":"Haiti"	,	"Rank":176	,	"MoslemPopulation":"1000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Haiti.png"},
    {"CountryName":"Honduras"	,	"Rank":92	,	"MoslemPopulation":"15627000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Honduras.png"},
    {"CountryName":"Hong Kong"	,	"Rank":27	,	"MoslemPopulation":"705000"	,	"Percentage":1.3	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Hong-Kong.png"},
    {"CountryName":"Hungary"	,	"Rank":31	,	"MoslemPopulation":"91000"	,	"Percentage":0.3	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Hungary.png"},
    {"CountryName":"Iceland"	,	"Rank":4	,	"MoslemPopulation":"80024000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Iceland.png"},
    {"CountryName":"India"	,	"Rank":89	,	"MoslemPopulation":"7000"	,	"Percentage":14.6	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/India.png"},
    {"CountryName":"Indonesia"	,	"Rank":140	,	"MoslemPopulation":"1564000"	,	"Percentage":88.1	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Indonesia.png"},
    {"CountryName":"Iran"	,	"Rank":163	,	"MoslemPopulation":"3598000"	,	"Percentage":99.7	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Iran.png"},
    {"CountryName":"Iraq"	,	"Rank":201	,	"MoslemPopulation":"95000"	,	"Percentage":98.9	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Iraq.png"},
    {"CountryName":"Ireland"	,	"Rank":3	,	"MoslemPopulation":"2000"	,	"Percentage":0.9	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Ireland.png"},
    {"CountryName":"Isle of Man"	,"Rank":205	,	"MoslemPopulation":"59000"	,	"Percentage":0.2	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/Isle-of-Man.png"},
    {"CountryName":"Israel"	,	"Rank":61	,	"MoslemPopulation":"< 1000"	,	"Percentage":17.7	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Israel.png"},
    {"CountryName":"Italy"	,	"Rank":33	,	"MoslemPopulation":"< 1000"	,	"Percentage":2.6	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Italy.png"},
    {"CountryName":"Ivory Coast"	,"Rank":22	,	"MoslemPopulation":"226000"	,	"Percentage":36.9	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Ivory Coast.png"},
    {"CountryName":"Jamaica"	,	"Rank":47	,	"MoslemPopulation":"2868000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Jamaica.png"},
    {"CountryName":"Japan"	,	"Rank":29	,	"MoslemPopulation":"2000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"Yes"	,	"Flag":"res/Japan.png"},
    {"CountryName":"Jordan"	,	"Rank":77	,	"MoslemPopulation":"< 1000"	,	"Percentage":98.8	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Jordan.png"},
    {"CountryName":"Kazakhstan"	,	"Rank":107	,	"MoslemPopulation":"655000"	,	"Percentage":56.4	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Kazakhstan.png"},
    {"CountryName":"Kenya"	,	"Rank":144	,	"MoslemPopulation":"< 1000"	,	"Percentage":7	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Kenya.png"},
    {"CountryName":"Kiribati"	,	"Rank":115	,	"MoslemPopulation":"20000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Oceania"	,	"Developed":"No"	,	"Flag":"res/Kiribati.png"},
    {"CountryName":"Kuwait"	,	"Rank":48	,	"MoslemPopulation":"29047000"	,	"Percentage":86.4	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Kuwait.png"},
    {"CountryName":"Kyrgyzstan"	,	"Rank":137	,	"MoslemPopulation":"2000"	,	"Percentage":88.8	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Kyrgyzstan.png"},
    {"CountryName":"Laos"	,	"Rank":183	,	"MoslemPopulation":"< 1000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Laos.png"},
    {"CountryName":"Latvia"	,	"Rank":28	,	"MoslemPopulation":"55000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Latvia.png"},
    {"CountryName":"Lebanon"	,	"Rank":158	,	"MoslemPopulation":"1900000"	,	"Percentage":59.7	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Lebanon.png"},
    {"CountryName":"Lesotho"	,	"Rank":63	,	"MoslemPopulation":"2011000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Lesotho.png"},
    {"CountryName":"Liberia"	,	"Rank":194	,	"MoslemPopulation":"< 1000"	,	"Percentage":12.8	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Liberia.png"},
    {"CountryName":"Libya"	,	"Rank":196	,	"MoslemPopulation":"< 1000"	,	"Percentage":96.6	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Libya.png"},
    {"CountryName":"Liechtenstein"	,"Rank":105	,	"MoslemPopulation":"< 1000"	,	"Percentage":4.8	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/Liechtenstein.png"},
    {"CountryName":"Lithuania"	,	"Rank":35	,	"MoslemPopulation":"204847000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Lithuania.png"},
    {"CountryName":"Luxembourg"	,	"Rank":2	,	"MoslemPopulation":"2000"	,	"Percentage":2.3	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Luxembourg.png"},
    {"CountryName":"Macau"	,	"Rank":83	,	"MoslemPopulation":"9000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Macau.png"},
    {"CountryName":"Madagascar"	,	"Rank":142	,	"MoslemPopulation":"4000"	,	"Percentage":1.1	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Madagascar.png"},
    {"CountryName":"Malawi"	,	"Rank":129	,	"MoslemPopulation":"< 1000"	,	"Percentage":12.8	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Malawi.png"},
    {"CountryName":"Malaysia"	,	"Rank":38	,	"MoslemPopulation":"853000"	,	"Percentage":61.4	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Malaysia.png"},
    {"CountryName":"Maldives"	,	"Rank":104	,	"MoslemPopulation":"< 1000"	,	"Percentage":98.4	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Maldives.png"},
    {"CountryName":"Mali"	,	"Rank":130	,	"MoslemPopulation":"7960000"	,	"Percentage":92.4	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Mali.png"},
    {"CountryName":"Malta"	,	"Rank":30	,	"MoslemPopulation":"11000"	,	"Percentage":0.3	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Malta.png"},
    {"CountryName":"Marshall Islands"	,"Rank":187	,	"MoslemPopulation":"393000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Oceania"	,	"Developed":"No"	,	"Flag":"res/Marshall-Islands.png"},
    {"CountryName":"Mauritania"	,	"Rank":195	,	"MoslemPopulation":"< 1000"	,	"Percentage":99.2	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Mauritania.png"},
    {"CountryName":"Mauritius"	,	"Rank":42	,	"MoslemPopulation":"1583000"	,	"Percentage":16.6	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Mauritius.png"},
    {"CountryName":"Mayotte"	,	"Rank":208	,	"MoslemPopulation":"109000"	,	"Percentage":98.8	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Mayotte.png"},
    {"CountryName":"Mexico"	,	"Rank":55	,	"MoslemPopulation":"523000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Mexico.png"},
    {"CountryName":"Moldova"	,	"Rank":110	,	"MoslemPopulation":"1000"	,	"Percentage":0.4	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/Moldova.png"},
    {"CountryName":"Monaco"	,	"Rank":62	,	"MoslemPopulation":"220000"	,	"Percentage":0.5	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/Monaco.png"},
    {"CountryName":"Mongolia"	,	"Rank":97	,	"MoslemPopulation":"< 1000"	,	"Percentage":4.4	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Mongolia.png"},
    {"CountryName":"Morocco"	,	"Rank":119	,	"MoslemPopulation":"638000"	,	"Percentage":99.9	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Morocco.png"},
    {"CountryName":"Mozambique"	,	"Rank":96	,	"MoslemPopulation":"< 1000"	,	"Percentage":22.8	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Mozambique.png"},
    {"CountryName":"Namibia"	,	"Rank":45	,	"MoslemPopulation":"6397000"	,	"Percentage":0.4	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Namibia.png"},
    {"CountryName":"Nepal"	,	"Rank":151	,	"MoslemPopulation":"1725000"	,	"Percentage":4.2	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Nepal.png"},
    {"CountryName":"Netherlands"	,"Rank":9	,	"MoslemPopulation":"< 1000"	,	"Percentage":5.5	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Netherlands.png"},
    {"CountryName":"Netherlands Antilles"	,"Rank":95	,	"MoslemPopulation":"3000"	,	"Percentage":0.2	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/Netherlands-Antilles.png"},
    {"CountryName":"New Caledonia"	,"Rank":150	,	"MoslemPopulation":"1021000"	,	"Percentage":2.8	,	"OIC":"No"	,	"Continent":"Oceania"	,	"Developed":"No"	,	"Flag":"res/New-Caledonia.png"},
    {"CountryName":"New Zealand"	,"Rank":1	,	"MoslemPopulation":"< 1000"	,	"Percentage":0.9	,	"OIC":"No"	,	"Continent":"Oceania"	,	"Developed":"Yes"	,	"Flag":"res/New-Zealand.png"},
    {"CountryName":"Nicaragua"	,	"Rank":81	,	"MoslemPopulation":"32381000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Nicaragua.png"},
    {"CountryName":"Niger"	,	"Rank":189	,	"MoslemPopulation":"14000"	,	"Percentage":98.3	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Niger.png"},
    {"CountryName":"Nigeria"	,	"Rank":174	,	"MoslemPopulation":"6404000"	,	"Percentage":47.9	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Nigeria.png"},
    {"CountryName":"North Korea"	,"Rank":138	,	"MoslemPopulation":"4171000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/North-Korea.png"},
    {"CountryName":"Northern Mariana Islands"	,"Rank":119	,	"MoslemPopulation":"60000"	,	"Percentage":0.7	,	"OIC":"No"	,	"Continent":"Oceania"	,	"Developed":"No"	,	"Flag":"res/Northern Mariana Islands.png"},
    {"CountryName":"Norway"	,	"Rank":12	,	"MoslemPopulation":"54000"	,	"Percentage":3	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Norway.png"},
    {"CountryName":"Oman"	,	"Rank":99	,	"MoslemPopulation":"399000"	,	"Percentage":87.7	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Oman.png"},
    {"CountryName":"Pakistan"	,	"Rank":147	,	"MoslemPopulation":"211000"	,	"Percentage":96.4	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Pakistan.png"},
    {"CountryName":"Palau"	,	"Rank":143	,	"MoslemPopulation":"49000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Oceania"	,	"Developed":"No"	,	"Flag":"res/Palau.png"},
    {"CountryName":"Panama"	,	"Rank":39	,	"MoslemPopulation":"43000"	,	"Percentage":0.7	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Panama.png"},
    {"CountryName":"Papua New Guinea"	,"Rank":119	,	"MoslemPopulation":"713000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Oceania"	,	"Developed":"No"	,	"Flag":"res/Papua-New-Guinea.png"},
    {"CountryName":"Paraguay"	,	"Rank":136	,	"MoslemPopulation":"< 1000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"South America"	,	"Developed":"No"	,	"Flag":"res/Paraguay.png"},
    {"CountryName":"Peru"	,	"Rank":88	,	"MoslemPopulation":"< 1000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"South America"	,	"Developed":"No"	,	"Flag":"res/Peru.png"},
    {"CountryName":"Philippines"	,"Rank":59	,	"MoslemPopulation":"3000"	,	"Percentage":5.1	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Philippines.png"},
    {"CountryName":"Poland"	,	"Rank":41	,	"MoslemPopulation":"1287000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Poland.png"},
    {"CountryName":"Portugal"	,	"Rank":16	,	"MoslemPopulation":"145000"	,	"Percentage":0.6	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Portugal.png"},
    {"CountryName":"Puerto Rico"	,"Rank":113	,	"MoslemPopulation":"< 1000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Puerto-Rico.png"},
    {"CountryName":"Qatar"	,	"Rank":112	,	"MoslemPopulation":"19000"	,	"Percentage":77.5	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Qatar.png"},
    {"CountryName":"Republic of Congo"	,"Rank":182	,	"MoslemPopulation":"74660000"	,	"Percentage":1.6	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Republic-of-the-Congo.png"},
    {"CountryName":"Republic of Macedonia"	,"Rank":98	,	"MoslemPopulation":"144000"	,	"Percentage":34.9	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/Macedonia.png"},
    {"CountryName":"Romania"	,	"Rank":66	,	"MoslemPopulation":"17139000"	,	"Percentage":0.3	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Romania.png"},
    {"CountryName":"Russia"	,	"Rank":91	,	"MoslemPopulation":"1000"	,	"Percentage":11.7	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Russia.png"},
    {"CountryName":"Rwanda"	,	"Rank":135	,	"MoslemPopulation":"280000"	,	"Percentage":1.8	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Rwanda.png"},
    {"CountryName":"Samoa"	,	"Rank":146	,	"MoslemPopulation":"9231000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Oceania"	,	"Developed":"No"	,	"Flag":"res/Samoa.png"},
    {"CountryName":"San Marino"	,	"Rank":79	,	"MoslemPopulation":"< 1000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/San-Marino.png"},
    {"CountryName":"Sao Tome and Principe"	,"Rank":192	,	"MoslemPopulation":"2595000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Sao-Tome-and-Principe.png"},
    {"CountryName":"Saudi Arabia"	,"Rank":131	,	"MoslemPopulation":"< 1000"	,	"Percentage":97.1	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Saudi-Arabia.png"},
    {"CountryName":"Senegal"	,	"Rank":109	,	"MoslemPopulation":"148607000"	,	"Percentage":95.9	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Senegal.png"},
    {"CountryName":"Serbia"	,	"Rank":185	,	"MoslemPopulation":"4060000"	,	"Percentage":3.7	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/Serbia.png"},
    {"CountryName":"Seychelles"	,	"Rank":71	,	"MoslemPopulation":"< 1000"	,	"Percentage":1.1	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Seychelles.png"},
    {"CountryName":"Sierra Leone"	,"Rank":168	,	"MoslemPopulation":"940000"	,	"Percentage":71.5	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Sierra-Leone.png"},
    {"CountryName":"Singapore"	,	"Rank":37	,	"MoslemPopulation":"31108000"	,	"Percentage":14.9	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Singapore.png"},
    {"CountryName":"Slovakia"	,	"Rank":31	,	"MoslemPopulation":"25000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Slovakia.png"},
    {"CountryName":"Slovenia"	,	"Rank":26	,	"MoslemPopulation":"8693000"	,	"Percentage":2.4	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Slovenia.png"},
    {"CountryName":"Solomon Islands"	,"Rank":190	,	"MoslemPopulation":"2869000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Oceania"	,	"Developed":"No"	,	"Flag":"res/Solomon-Islands.png"},
    {"CountryName":"Somalia"	,	"Rank":206	,	"MoslemPopulation":"4000"	,	"Percentage":98.6	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Somalia.png"},
    {"CountryName":"South Africa"	,"Rank":50	,	"MoslemPopulation":"2636000"	,	"Percentage":1.5	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/South-Africa.png"},
    {"CountryName":"South Korea"	,"Rank":106	,	"MoslemPopulation":"25000"	,	"Percentage":0.2	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/South-Korea.png"},
    {"CountryName":"Spain"	,	"Rank":23	,	"MoslemPopulation":"< 1000"	,	"Percentage":2.3	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Spain.png"},
    {"CountryName":"Sri Lanka"	,	"Rank":116	,	"MoslemPopulation":"65000"	,	"Percentage":8.5	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Sri-Lanka.png"},
    {"CountryName":"St. Kitts and Nevis"	,"Rank":117	,"MoslemPopulation":"1168000"	,	"Percentage":0.3	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Saint-Kitts-and-Nevis.png"},
    {"CountryName":"St. Lucia"	,	"Rank":52	,	"MoslemPopulation":"1000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Saint-Lucia.png"},
    {"CountryName":"St. Vincent and the Grenadines"	,	"Rank":44	,	"MoslemPopulation":"185000"	,	"Percentage":1.7	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Saint-Vincent-and-the-Grenadines.png"},
    {"CountryName":"Sudan"	,	"Rank":202	,	"MoslemPopulation":"200000"	,	"Percentage":71.4	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Sudan.png"},
    {"CountryName":"Suriname"	,	"Rank":100	,	"MoslemPopulation":"475000"	,	"Percentage":15.9	,	"OIC":"Yes"	,	"Continent":"South America"	,	"Developed":"No"	,	"Flag":"res/Suriname.png"},
    {"CountryName":"Swaziland"	,	"Rank":156	,	"MoslemPopulation":"30855000"	,	"Percentage":0.2	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Swaziland.png"},
    {"CountryName":"Sweden"	,	"Rank":15	,	"MoslemPopulation":"< 1000"	,	"Percentage":4.9	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Sweden.png"},
    {"CountryName":"Switzerland"	,"Rank":13	,	"MoslemPopulation":"42000"	,	"Percentage":5.7	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/Switzerland.png"},
    {"CountryName":"Syria"	,	"Rank":186	,	"MoslemPopulation":"23308000"	,	"Percentage":92.8	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Syria.png"},
    {"CountryName":"Tajikistan"	,	"Rank":176	,	"MoslemPopulation":"4000"	,	"Percentage":99	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Tajikistan.png"},
    {"CountryName":"Tanzania"	,	"Rank":74	,	"MoslemPopulation":"216000"	,	"Percentage":29.9	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Tanzania.png"},
    {"CountryName":"Thailand"	,	"Rank":78	,	"MoslemPopulation":"111000"	,	"Percentage":5.8	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Thailand.png"},
    {"CountryName":"Timor-Leste"	,"Rank":107	,	"MoslemPopulation":"2000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Timor Leste.png"},
    {"CountryName":"Togo"	,	"Rank":172	,	"MoslemPopulation":"< 1000"	,	"Percentage":12.2	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Togo.png"},
    {"CountryName":"Tonga"	,	"Rank":155	,	"MoslemPopulation":"< 1000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Oceania"	,	"Developed":"No"	,	"Flag":"res/Tonga.png"},
    {"CountryName":"Trinidad and Tobago"	,"Rank":40	,"MoslemPopulation":"< 1000"	,	"Percentage":5.8	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/Trinidad-and-Tobago.png"},
    {"CountryName":"Tunisia"	,	"Rank":83	,	"MoslemPopulation":"1000000"	,	"Percentage":99.8	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Tunisia.png"},
    {"CountryName":"Turkey"	,	"Rank":103	,	"MoslemPopulation":"8795000"	,	"Percentage":98.6	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Turkey.png"},
    {"CountryName":"Turkmenistan"	,"Rank":173	,	"MoslemPopulation":"403000"	,	"Percentage":93.3	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Turkmenistan.png"},
    {"CountryName":"U.S. Virgin Islands"	,"Rank":149	,"MoslemPopulation":"75000"	,	"Percentage":0.1	,	"OIC":"No"	,	"Continent":"North America"	,	"Developed":"No"	,	"Flag":"res/US-Virgin-Islands.png"},
    {"CountryName":"Uganda"	,	"Rank":73	,	"MoslemPopulation":"1000"	,	"Percentage":12	,	"OIC":"Yes"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Uganda.png"},
    {"CountryName":"Ukraine"	,	"Rank":102	,	"MoslemPopulation":"178097000"	,	"Percentage":0.9	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"No"	,	"Flag":"res/Ukraine.png"},
    {"CountryName":"United Arab Emirates"	,"Rank":66	,"MoslemPopulation":"< 1000"	,	"Percentage":76	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/United-Arab-Emirates.png"},
    {"CountryName":"United Kingdom"	,"Rank":8	,	"MoslemPopulation":"2000"	,	"Percentage":4.6	,	"OIC":"No"	,	"Continent":"Europe"	,	"Developed":"Yes"	,	"Flag":"res/United-Kingdom.png"},
    {"CountryName":"United States"	,"Rank":25	,	"MoslemPopulation":"1000"	,	"Percentage":0.8	,	"OIC":"No"	,	"Continent":"South America"	,	"Developed":"Yes"	,	"Flag":"res/United-States.png"},
    {"CountryName":"Uruguay"	,	"Rank":48	,	"MoslemPopulation":"< 1000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"South America"	,	"Developed":"No"	,	"Flag":"res/Uruguay.png"},
    {"CountryName":"Uzbekistan"	,	"Rank":174	,	"MoslemPopulation":"< 1000"	,	"Percentage":96.5	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Uzbekistan.png"},
    {"CountryName":"Vanuatu"	,	"Rank":133	,	"MoslemPopulation":"25493000"	,	"Percentage":0.05	,	"OIC":"No"	,	"Continent":"Oceania"	,	"Developed":"No"	,	"Flag":"res/Vanuatu.png"},
    {"CountryName":"Venezuela"	,	"Rank":141	,	"MoslemPopulation":"721000"	,	"Percentage":0.3	,	"OIC":"No"	,	"Continent":"South America"	,	"Developed":"No"	,	"Flag":"res/Venezuela.png"},
    {"CountryName":"Vietnam"	,	"Rank":134	,	"MoslemPopulation":"12333000"	,	"Percentage":0.2	,	"OIC":"No"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Vietnam.png"},
    {"CountryName":"Yemen"	,	"Rank":198	,	"MoslemPopulation":"10000"	,	"Percentage":99	,	"OIC":"Yes"	,	"Continent":"Asia"	,	"Developed":"No"	,	"Flag":"res/Yemen.png"},
    {"CountryName":"Zambia"	,	"Rank":119	,	"MoslemPopulation":"73000"	,	"Percentage":0.4	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Zambia.png"},
    {"CountryName":"Zimbabwe"	,	"Rank":159	,	"MoslemPopulation":"84000"	,	"Percentage":0.9	,	"OIC":"No"	,	"Continent":"Africa"	,	"Developed":"No"	,	"Flag":"res/Zimbabwe.png"}
];